version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

  node:
    build:
      context: .
    ports:
      - "8888:8888"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
