version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - app-network

  couchdb:
    build:
      context: .
      dockerfile: docker/couchdb/Dockerfile
    restart: always
    ports:
      - "5984:5984"
    environment:
      - INSTANCE=couchdb
      - COUCHDB_SERVER=http://couchdb:5984
    networks:
      - backend-network
    volumes:
      - db_data:/opt/couchdb/data:rw

  node1:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    environment:
      - INSTANCE=node1
    ports:
      - "8888"
    networks:
      - app-network
      - backend-network
    links:
        - couchdb
  
  node2:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    environment:
      - INSTANCE=node2
    ports:
      - "8888"
    networks:
      - app-network
      - backend-network
    links:
        - couchdb

        

  node3:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    environment:
      - INSTANCE=node3
    ports:
      - "8888"
    networks:
      - app-network
      - backend-network
    links:
        - couchdb

secrets:
  my-db-password:
    file: ./docker/production.env 
    
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
  backend-network:
    driver: bridge
