# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker NGINX CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build and Push NGINX Docker Image to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: spyrogiants/pho2song-nginx
        registry: docker.io
        buildArgs: SSL_CERT=${{ secrets.SSL_CERT }}, SSL_CERT_KEY=${{ secrets.SSL_CERT_KEY }}
        directory: docker/nginx
        dockerfile: docker/nginx/Dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        


