# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json

    - run: npm ci

    - run: npm test
      env:
        IMAGGA_CLIENT_ID: ${{ secrets.IMAGGA_CLIENT_ID }}
        IMAGGA_CLIENT_SECRET: ${{ secrets.IMAGGA_CLIENT_SECRET }}

    - name: Build and Push App Docker Image to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: spyrogiants/pho2song
        registry: docker.io
        buildArgs: IMAGGA_CLIENT_ID=${{ secrets.IMAGGA_CLIENT_ID }}, IMAGGA_CLIENT_SECRET=${{ secrets.IMAGGA_CLIENT_SECRET }}, GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}, GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}, SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}, SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}, DB_USER=${{ secrets.DB_USER }}, DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        dockerfile: docker/node/Dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        addLatest: true

